<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/v1/assets/hardware-assets', operationId: 'assetsHardwareIndex', tags: ['Assets'], summary: 'Список единиц оборудования', parameters: [new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'employee_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/assets/hardware-assets', operationId: 'assetsHardwareStore', tags: ['Assets'], summary: 'Создать запись оборудования', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/HardwareAssetWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject')), new OA\Response(response: 422, description: 'Ошибка валидации', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/assets/hardware-assets/{hardware_asset}', operationId: 'assetsHardwareShow', tags: ['Assets'], summary: 'Оборудование', parameters: [new OA\Parameter(name: 'hardware_asset', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/assets/hardware-assets/{hardware_asset}', operationId: 'assetsHardwareUpdate', tags: ['Assets'], summary: 'Обновить оборудование', parameters: [new OA\Parameter(name: 'hardware_asset', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/HardwareAssetWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/assets/hardware-assets/{hardware_asset}', operationId: 'assetsHardwareDestroy', tags: ['Assets'], summary: 'Удалить запись', parameters: [new OA\Parameter(name: 'hardware_asset', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/assets/software-licenses', operationId: 'assetsLicensesIndex', tags: ['Assets'], summary: 'Список лицензий (withCount used_seats)', parameters: [new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/assets/software-licenses', operationId: 'assetsLicensesStore', tags: ['Assets'], summary: 'Создать лицензию', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/SoftwareLicenseWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/assets/software-licenses/{software_license}', operationId: 'assetsLicensesShow', tags: ['Assets'], summary: 'Лицензия и назначенные сотрудники', parameters: [new OA\Parameter(name: 'software_license', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/assets/software-licenses/{software_license}', operationId: 'assetsLicensesUpdate', tags: ['Assets'], summary: 'Обновить лицензию', parameters: [new OA\Parameter(name: 'software_license', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/SoftwareLicenseWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/assets/software-licenses/{software_license}', operationId: 'assetsLicensesDestroy', tags: ['Assets'], summary: 'Удалить лицензию', parameters: [new OA\Parameter(name: 'software_license', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Post(path: '/v1/assets/software-licenses/{software_license}/employees', operationId: 'assetsLicensesAttachEmployee', tags: ['Assets'], summary: 'Выдать место лицензии сотруднику', parameters: [new OA\Parameter(name: 'software_license', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/LicenseAttachRequest')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject')), new OA\Response(response: 422, description: 'Нет свободных мест', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/assets/software-licenses/{software_license}/employees/{employee}', operationId: 'assetsLicensesDetachEmployee', tags: ['Assets'], summary: 'Отозвать лицензию у сотрудника', parameters: [new OA\Parameter(name: 'software_license', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'employee', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
final class OpenApiOperationsAssets {}
