<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/v1/tickets/ticket-categories', operationId: 'ticketsCategoriesIndex', tags: ['Tickets'], summary: 'Категории заявок', parameters: [new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc']))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/tickets/ticket-categories', operationId: 'ticketsCategoriesStore', tags: ['Tickets'], summary: 'Создать категорию', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TicketCategoryWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/tickets/ticket-categories/{ticket_category}', operationId: 'ticketsCategoriesShow', tags: ['Tickets'], summary: 'Категория', parameters: [new OA\Parameter(name: 'ticket_category', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/tickets/ticket-categories/{ticket_category}', operationId: 'ticketsCategoriesUpdate', tags: ['Tickets'], summary: 'Обновить категорию', parameters: [new OA\Parameter(name: 'ticket_category', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/TicketCategoryWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/tickets/ticket-categories/{ticket_category}', operationId: 'ticketsCategoriesDestroy', tags: ['Tickets'], summary: 'Удалить категорию', parameters: [new OA\Parameter(name: 'ticket_category', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/tickets/records', operationId: 'ticketsRecordsIndex', tags: ['Tickets'], summary: 'Заявки (ресурс records)', parameters: [new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'ticket_category_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'priority', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'assignee_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'reporter_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/tickets/records', operationId: 'ticketsRecordsStore', tags: ['Tickets'], summary: 'Создать заявку', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TicketRecordWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/tickets/records/{record}', operationId: 'ticketsRecordsShow', tags: ['Tickets'], summary: 'Заявка с комментариями', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/tickets/records/{record}', operationId: 'ticketsRecordsUpdate', tags: ['Tickets'], summary: 'Обновить заявку', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/TicketRecordWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/tickets/records/{record}', operationId: 'ticketsRecordsDestroy', tags: ['Tickets'], summary: 'Удалить заявку', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/tickets/records/{record}/ticket-comments', operationId: 'ticketsCommentsIndex', tags: ['Tickets'], summary: 'Комментарии к заявке', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc']))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/tickets/records/{record}/ticket-comments', operationId: 'ticketsCommentsStore', tags: ['Tickets'], summary: 'Добавить комментарий', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TicketCommentWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/tickets/records/{record}/ticket-comments/{ticket_comment}', operationId: 'ticketsCommentsShow', tags: ['Tickets'], summary: 'Комментарий', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'ticket_comment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/tickets/records/{record}/ticket-comments/{ticket_comment}', operationId: 'ticketsCommentsUpdate', tags: ['Tickets'], summary: 'Обновить комментарий', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'ticket_comment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/TicketCommentPatch')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/tickets/records/{record}/ticket-comments/{ticket_comment}', operationId: 'ticketsCommentsDestroy', tags: ['Tickets'], summary: 'Удалить комментарий', parameters: [new OA\Parameter(name: 'record', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'ticket_comment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
final class OpenApiOperationsTickets {}
