<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/v1/org/departments', operationId: 'orgDepartmentsIndex', tags: ['Org'], summary: 'Список отделов', parameters: [new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc']))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/org/departments', operationId: 'orgDepartmentsStore', tags: ['Org'], summary: 'Создать отдел', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/DepartmentWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject')), new OA\Response(response: 422, description: 'Ошибка валидации', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/org/departments/{department}', operationId: 'orgDepartmentsShow', tags: ['Org'], summary: 'Отдел с сотрудниками', parameters: [new OA\Parameter(name: 'department', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/org/departments/{department}', operationId: 'orgDepartmentsUpdate', tags: ['Org'], summary: 'Обновить отдел', parameters: [new OA\Parameter(name: 'department', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/DepartmentWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/org/departments/{department}', operationId: 'orgDepartmentsDestroy', tags: ['Org'], summary: 'Удалить отдел', parameters: [new OA\Parameter(name: 'department', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/org/employees', operationId: 'orgEmployeesIndex', tags: ['Org'], summary: 'Список сотрудников', parameters: [new OA\Parameter(name: 'department_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'job_title', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/org/employees', operationId: 'orgEmployeesStore', tags: ['Org'], summary: 'Создать сотрудника', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/EmployeeWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject')), new OA\Response(response: 422, description: 'Ошибка валидации', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/org/employees/{employee}', operationId: 'orgEmployeesShow', tags: ['Org'], summary: 'Сотрудник', parameters: [new OA\Parameter(name: 'employee', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/org/employees/{employee}', operationId: 'orgEmployeesUpdate', tags: ['Org'], summary: 'Обновить сотрудника', parameters: [new OA\Parameter(name: 'employee', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/EmployeeWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/org/employees/{employee}', operationId: 'orgEmployeesDestroy', tags: ['Org'], summary: 'Удалить сотрудника', parameters: [new OA\Parameter(name: 'employee', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/org/teams', operationId: 'orgTeamsIndex', tags: ['Org'], summary: 'Список команд', parameters: [new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc']))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/org/teams', operationId: 'orgTeamsStore', tags: ['Org'], summary: 'Создать команду', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TeamWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/org/teams/{team}', operationId: 'orgTeamsShow', tags: ['Org'], summary: 'Команда с участниками', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/org/teams/{team}', operationId: 'orgTeamsUpdate', tags: ['Org'], summary: 'Обновить команду', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/TeamWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/org/teams/{team}', operationId: 'orgTeamsDestroy', tags: ['Org'], summary: 'Удалить команду', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Post(path: '/v1/org/teams/{team}/employees', operationId: 'orgTeamsAttachEmployee', tags: ['Org'], summary: 'Добавить сотрудника в команду', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TeamAttachRequest')), responses: [new OA\Response(response: 200, description: 'Команда с составом', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/org/teams/{team}/employees/{employee}', operationId: 'orgTeamsDetachEmployee', tags: ['Org'], summary: 'Убрать сотрудника из команды', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'employee', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Команда с составом', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
final class OpenApiOperationsOrg {}
