<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/v1/hiring/vacancies', operationId: 'hiringVacanciesIndex', tags: ['Hiring'], summary: 'Вакансии', parameters: [new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'department_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/hiring/vacancies', operationId: 'hiringVacanciesStore', tags: ['Hiring'], summary: 'Создать вакансию', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/VacancyWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/hiring/vacancies/{vacancy}', operationId: 'hiringVacanciesShow', tags: ['Hiring'], summary: 'Вакансия с откликами', parameters: [new OA\Parameter(name: 'vacancy', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/hiring/vacancies/{vacancy}', operationId: 'hiringVacanciesUpdate', tags: ['Hiring'], summary: 'Обновить вакансию', parameters: [new OA\Parameter(name: 'vacancy', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/VacancyWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/hiring/vacancies/{vacancy}', operationId: 'hiringVacanciesDestroy', tags: ['Hiring'], summary: 'Удалить вакансию', parameters: [new OA\Parameter(name: 'vacancy', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/hiring/vacancies/{vacancy}/applications', operationId: 'hiringVacanciesApplicationsIndex', tags: ['Hiring'], summary: 'Отклики на вакансию', parameters: [new OA\Parameter(name: 'vacancy', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'stage', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'q', in: 'query', description: 'Кандидат: имя, email', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/hiring/candidates', operationId: 'hiringCandidatesIndex', tags: ['Hiring'], summary: 'Кандидаты', parameters: [new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/hiring/candidates', operationId: 'hiringCandidatesStore', tags: ['Hiring'], summary: 'Создать кандидата', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CandidateWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/hiring/candidates/{candidate}', operationId: 'hiringCandidatesShow', tags: ['Hiring'], summary: 'Кандидат с откликами', parameters: [new OA\Parameter(name: 'candidate', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/hiring/candidates/{candidate}', operationId: 'hiringCandidatesUpdate', tags: ['Hiring'], summary: 'Обновить кандидата', parameters: [new OA\Parameter(name: 'candidate', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/CandidateWrite')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/hiring/candidates/{candidate}', operationId: 'hiringCandidatesDestroy', tags: ['Hiring'], summary: 'Удалить кандидата', parameters: [new OA\Parameter(name: 'candidate', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/hiring/job-applications', operationId: 'hiringApplicationsIndex', tags: ['Hiring'], summary: 'Все отклики', parameters: [new OA\Parameter(name: 'vacancy_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'candidate_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'stage', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'q', in: 'query', description: 'Кандидат или название вакансии', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/hiring/job-applications', operationId: 'hiringApplicationsStore', tags: ['Hiring'], summary: 'Создать отклик (vacancy_id + candidate_id)', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/JobApplicationWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject')), new OA\Response(response: 422, description: 'Дубликат или валидация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/hiring/job-applications/{job_application}', operationId: 'hiringApplicationsShow', tags: ['Hiring'], summary: 'Отклик с интервью', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/hiring/job-applications/{job_application}', operationId: 'hiringApplicationsUpdate', tags: ['Hiring'], summary: 'Обновить этап отклика', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/JobApplicationPatch')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/hiring/job-applications/{job_application}', operationId: 'hiringApplicationsDestroy', tags: ['Hiring'], summary: 'Удалить отклик', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
#[OA\Get(path: '/v1/hiring/job-applications/{job_application}/interviews', operationId: 'hiringInterviewsIndex', tags: ['Hiring'], summary: 'Интервью по отклику', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'q', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'sort', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['asc', 'desc']))], responses: [new OA\Response(response: 200, description: 'Пагинация', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Post(path: '/v1/hiring/job-applications/{job_application}/interviews', operationId: 'hiringInterviewsStore', tags: ['Hiring'], summary: 'Запланировать интервью', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/InterviewWrite')), responses: [new OA\Response(response: 201, description: 'Создано', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Get(path: '/v1/hiring/job-applications/{job_application}/interviews/{interview}', operationId: 'hiringInterviewsShow', tags: ['Hiring'], summary: 'Интервью', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'interview', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Put(path: '/v1/hiring/job-applications/{job_application}/interviews/{interview}', operationId: 'hiringInterviewsUpdate', tags: ['Hiring'], summary: 'Обновить интервью', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'interview', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/InterviewPatch')), responses: [new OA\Response(response: 200, description: 'OK', content: new OA\JsonContent(ref: '#/components/schemas/JsonObject'))])]
#[OA\Delete(path: '/v1/hiring/job-applications/{job_application}/interviews/{interview}', operationId: 'hiringInterviewsDestroy', tags: ['Hiring'], summary: 'Удалить интервью', parameters: [new OA\Parameter(name: 'job_application', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'interview', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Без тела')])]
final class OpenApiOperationsHiring {}
